# !boxes -d shell -p a1 -s 80

################################################################################
#                                                                              #
# General configuration for posts, its title link and rendering                #
#                                                                              #
################################################################################
auto: false
pygments: true
permalink: /blog/:year/:month/:day/:title
markdown: maruku
maruku:
    use_divs: true
    use_tex: true
    png_engine: blahtex
    png_dir: images/latex/
    png_url: /images/latex/

exclude:
    - Makefile
    - README.md
    - links.txt
    - CNAME

################################################################################
#                                                                              #
# Website configuration                                                        #
#                                                                              #
################################################################################
# FIXME: why are we keeping domain and base_url at the same time? Remove domain
# and its dependency in atom feed, sitemap generation plugin
domain: erenturkay.com

# url prefix for loading images, css in different domains. No slahs at the end.
base_url: http://erenturkay.com

#paginate: 2
#paginate_file: blog/index.html

disqus_developer: 1
disqus_shortname: erenturkayblog
sitemap_exclude: /test/

google_analytics_id: UA-35983607-1

# number of posts in the main page as "Latest entries"
num_of_post_in_main: 3

description: Eren Türkay'ın kişisel web sayfası.

             Uzun zamandır aktif olarak özgür yazılım geliştiriyorum ve
             kullanıyorum. Eski bir Pardus geliştiricisiyim. Amatör Telsizciyim
             _(DE TA1AET)_. Gömülü sistemler, linux, bilgi güvenliği, ağ,
             kablosuz iletişim, programlama dilleri, işletim sistemleri, afet ve
             acil durum haberleşmesi gibi konular ile ilgileniyorum.

            Teknik konular dışında salsa bachata ve merengue gibi latin dansları
            ile ilgileniyorum. Zaman buldukça tüplü dalış yapıyorum, 1 yıldız
            CMAS lisansına sahibim.

meta:
    - name: keywords 
      content: Eren Türkay, Eren Turkay, kimdir, blog, qwxzcv,
               qwzxcv.wordpress.com, linux, pardus, özgürlükiçin,
               amatör telsiz, hamradio
